"""Declarative registry of public news feeds.

Data only — no logic. Each entry drives one parallel fetch:

    id        cache key
    url       public RSS/Atom endpoint
    source    display name for the terminal UI
    category  UI filter bucket (WORLD, MARKETS, BULGARIA, ...)
    region    UI filter bucket; BULGARIA/BALKANS activate the local feed set
    language  ISO code for non-English feeds (empty means English)
"""

NEWS_FEEDS: list[dict[str, str]] = [
    {
        "id": "google-global",
        "url": "https://news.google.com/rss/search?q=world+OR+markets+OR+economy+OR+politics+OR+technology+OR+Europe&hl=en&gl=US&ceid=US%3Aen",
        "source": "GOOGLE NEWS INDEX",
        "category": "WORLD",
        "region": "GLOBAL",
        "language": "en",
    },
    {
        "id": "ap-news",
        "url": "https://news.google.com/rss/search?q=site:apnews.com&hl=en-US&gl=US&ceid=US:en",
        "source": "AP NEWS",
        "category": "WORLD",
        "region": "GLOBAL",
        "language": "en",
    },
    {
        "id": "reuters-world",
        "url": "https://news.google.com/rss/search?q=site:reuters.com+world&hl=en-US&gl=US&ceid=US:en",
        "source": "REUTERS",
        "category": "WORLD",
        "region": "GLOBAL",
        "language": "en",
    },
    {
        "id": "cnn-world",
        "url": "https://news.google.com/rss/search?q=site:cnn.com+world+news+when:1d&hl=en-US&gl=US&ceid=US:en",
        "source": "CNN",
        "category": "WORLD",
        "region": "GLOBAL",
        "language": "en",
    },
    {
        "id": "bloomberg",
        "url": "https://www.bloomberg.com/feeds/news.rss",
        "source": "BLOOMBERG",
        "category": "WORLD",
        "region": "GLOBAL",
    },
    {
        "id": "bloomberg-markets",
        "url": "https://feeds.bloomberg.com/markets/news.rss",
        "source": "BLOOMBERG",
        "category": "MARKETS",
        "region": "GLOBAL",
    },
    {
        "id": "bloomberg-business",
        "url": "https://feeds.bloomberg.com/business/news.rss",
        "source": "BLOOMBERG",
        "category": "BUSINESS",
        "region": "GLOBAL",
    },
    {
        "id": "bloomberg-tech",
        "url": "https://feeds.bloomberg.com/technology/news.rss",
        "source": "BLOOMBERG",
        "category": "TECH",
        "region": "GLOBAL",
    },
    {
        "id": "bloomberg-economics",
        "url": "https://feeds.bloomberg.com/economics/news.rss",
        "source": "BLOOMBERG",
        "category": "ECONOMICS",
        "region": "GLOBAL",
    },
    {
        "id": "bbc-world",
        "url": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "source": "BBC",
        "category": "WORLD",
        "region": "GLOBAL",
    },
    {
        "id": "bbc-business",
        "url": "https://feeds.bbci.co.uk/news/business/rss.xml",
        "source": "BBC",
        "category": "BUSINESS",
        "region": "GLOBAL",
    },
    {
        "id": "bbc-politics",
        "url": "https://feeds.bbci.co.uk/news/politics/rss.xml",
        "source": "BBC",
        "category": "POLITICS",
        "region": "GLOBAL",
    },
    {
        "id": "bbc-tech",
        "url": "https://feeds.bbci.co.uk/news/technology/rss.xml",
        "source": "BBC",
        "category": "TECH",
        "region": "GLOBAL",
    },
    {
        "id": "bbc-europe",
        "url": "https://feeds.bbci.co.uk/news/world/europe/rss.xml",
        "source": "BBC",
        "category": "EUROPE",
        "region": "EUROPE",
    },
    {
        "id": "guardian-world",
        "url": "https://www.theguardian.com/world/rss",
        "source": "THE GUARDIAN",
        "category": "WORLD",
        "region": "GLOBAL",
    },
    {
        "id": "guardian-business",
        "url": "https://www.theguardian.com/business/rss",
        "source": "THE GUARDIAN",
        "category": "BUSINESS",
        "region": "GLOBAL",
    },
    {
        "id": "guardian-tech",
        "url": "https://www.theguardian.com/technology/rss",
        "source": "THE GUARDIAN",
        "category": "TECH",
        "region": "GLOBAL",
    },
    {
        "id": "guardian-politics",
        "url": "https://www.theguardian.com/politics/rss",
        "source": "THE GUARDIAN",
        "category": "POLITICS",
        "region": "GLOBAL",
    },
    {
        "id": "cnbc-markets",
        "url": "https://www.cnbc.com/id/100003114/device/rss/rss.html",
        "source": "CNBC",
        "category": "MARKETS",
        "region": "GLOBAL",
    },
    {
        "id": "marketwatch",
        "url": "https://feeds.marketwatch.com/marketwatch/topstories/",
        "source": "MARKETWATCH",
        "category": "MARKETS",
        "region": "GLOBAL",
    },
    {
        "id": "investing",
        "url": "https://www.investing.com/rss/news_25.rss",
        "source": "INVESTING.COM",
        "category": "MARKETS",
        "region": "GLOBAL",
    },
    {
        "id": "euronews",
        "url": "https://www.euronews.com/rss?level=theme&name=news",
        "source": "EURONEWS",
        "category": "EUROPE",
        "region": "EUROPE",
    },
    {
        "id": "france24",
        "url": "https://www.france24.com/en/rss",
        "source": "FRANCE 24",
        "category": "WORLD",
        "region": "GLOBAL",
    },
    {
        "id": "dnevnik",
        "url": "https://www.dnevnik.bg/rss/",
        "source": "DNEVNIK",
        "category": "BULGARIA",
        "region": "BULGARIA",
        "language": "bg",
        "country": "BG",
    },
    {
        "id": "capital",
        "url": "https://www.capital.bg/rss/",
        "source": "CAPITAL",
        "category": "BUSINESS",
        "region": "BULGARIA",
        "language": "bg",
        "country": "BG",
    },
    {
        "id": "novinite",
        "url": "https://novinite.com/services/news_rdf.php",
        "source": "NOVINITE",
        "category": "BULGARIA",
        "region": "BULGARIA",
        "language": "en",
        "country": "BG",
    },
    {
        "id": "offnews",
        "url": "https://offnews.bg/rss/all",
        "source": "OFFNEWS",
        "category": "BULGARIA",
        "region": "BULGARIA",
        "language": "bg",
        "country": "BG",
    },
    {
        "id": "sofia-globe",
        "url": "https://sofiaglobe.com/feed/",
        "source": "SOFIA GLOBE",
        "category": "BULGARIA",
        "region": "BULGARIA",
        "language": "en",
        "country": "BG",
    },
    {
        "id": "balkan-insight",
        "url": "https://balkaninsight.com/feed/",
        "source": "BALKAN INSIGHT",
        "category": "BALKANS",
        "region": "BALKANS",
        "language": "en",
    },
]

BALKAN_RSS_FEEDS: list[dict[str, str]] = [
    {"id": "bta-bulgaria-en", "url": "https://www.bta.bg/en/news/bulgaria/rss", "source": "BTA", "category": "BULGARIA", "region": "BULGARIA", "language": "en", "country": "BG"},
    {"id": "bta-balkans-en", "url": "https://www.bta.bg/en/news/balkans/rss", "source": "BTA", "category": "BALKANS", "region": "BALKANS", "language": "en", "country": ""},
    {"id": "bta-bulgaria-bg", "url": "https://www.bta.bg/bg/news/bulgaria/rss", "source": "BTA", "category": "BULGARIA", "region": "BULGARIA", "language": "bg", "country": "BG"},
    {"id": "dnevnik-bg", "url": "https://www.dnevnik.bg/rss/", "source": "DNEVNIK", "category": "BULGARIA", "region": "BULGARIA", "language": "bg", "country": "BG"},
    {"id": "capital-bg", "url": "https://www.capital.bg/rss/", "source": "CAPITAL", "category": "BUSINESS", "region": "BULGARIA", "language": "bg", "country": "BG"},
    {"id": "rri-en", "url": "https://www.rri.ro/en/feed", "source": "RADIO ROMANIA INTERNATIONAL", "category": "ROMANIA", "region": "BALKANS", "language": "en", "country": "RO"},
    {"id": "vijesti-me", "url": "https://www.vijesti.me/rss", "source": "VIJESTI", "category": "MONTENEGRO", "region": "BALKANS", "language": "sr-Latn", "country": "ME"},
    {"id": "balkan-insight-al", "url": "https://balkaninsight.com/category/bi/albania/feed", "source": "BALKAN INSIGHT", "category": "ALBANIA", "region": "BALKANS", "language": "en", "country": "AL"},
    {"id": "balkan-insight-ba", "url": "https://balkaninsight.com/category/bi/bosnia-and-herzegovina/feed", "source": "BALKAN INSIGHT", "category": "BOSNIA AND HERZEGOVINA", "region": "BALKANS", "language": "en", "country": "BA"},
    {"id": "balkan-insight-bg", "url": "https://balkaninsight.com/category/bi/bulgaria/feed", "source": "BALKAN INSIGHT", "category": "BULGARIA", "region": "BULGARIA", "language": "en", "country": "BG"},
    {"id": "balkan-insight-hr", "url": "https://balkaninsight.com/category/bi/croatia/feed", "source": "BALKAN INSIGHT", "category": "CROATIA", "region": "BALKANS", "language": "en", "country": "HR"},
    {"id": "balkan-insight-xk", "url": "https://balkaninsight.com/category/bi/kosovo/feed", "source": "BALKAN INSIGHT", "category": "KOSOVO", "region": "BALKANS", "language": "en", "country": "XK"},
    {"id": "balkan-insight-mk", "url": "https://balkaninsight.com/category/bi/macedonia/feed", "source": "BALKAN INSIGHT", "category": "NORTH MACEDONIA", "region": "BALKANS", "language": "en", "country": "MK"},
    {"id": "balkan-insight-md", "url": "https://balkaninsight.com/category/bi/moldova/feed", "source": "BALKAN INSIGHT", "category": "MOLDOVA", "region": "BALKANS", "language": "en", "country": "MD"},
    {"id": "balkan-insight-me", "url": "https://balkaninsight.com/category/bi/montenegro/feed", "source": "BALKAN INSIGHT", "category": "MONTENEGRO", "region": "BALKANS", "language": "en", "country": "ME"},
    {"id": "balkan-insight-ro", "url": "https://balkaninsight.com/category/bi/romania/feed", "source": "BALKAN INSIGHT", "category": "ROMANIA", "region": "BALKANS", "language": "en", "country": "RO"},
    {"id": "balkan-insight-rs", "url": "https://balkaninsight.com/category/bi/serbia/feed", "source": "BALKAN INSIGHT", "category": "SERBIA", "region": "BALKANS", "language": "en", "country": "RS"},
]

BALKAN_COUNTRIES: dict[str, dict[str, str]] = {
    "BG": {"name": "Bulgaria", "locale": "bg", "edition": "BG:bg", "query": "България OR София OR Пловдив"},
    "RO": {"name": "Romania", "locale": "ro", "edition": "RO:ro", "query": "România OR București OR Moldova"},
    "GR": {"name": "Greece", "locale": "el", "edition": "GR:el", "query": "Ελλάδα OR Αθήνα"},
    "RS": {"name": "Serbia", "locale": "sr", "edition": "RS:sr", "query": "Srbija OR Beograd"},
    "MK": {"name": "North Macedonia", "locale": "mk", "edition": "MK:mk", "query": "Северна Македонија OR Скопје"},
    "AL": {"name": "Albania", "locale": "sq", "edition": "AL:sq", "query": "Shqipëri OR Tiranë"},
    "XK": {"name": "Kosovo", "locale": "sq", "edition": "XK:sq", "query": "Kosovë OR Prishtinë"},
    "ME": {"name": "Montenegro", "locale": "sr", "edition": "ME:sr", "query": "Crna Gora OR Podgorica"},
    "BA": {"name": "Bosnia and Herzegovina", "locale": "bs", "edition": "BA:bs", "query": "Bosna i Hercegovina OR Sarajevo"},
    "HR": {"name": "Croatia", "locale": "hr", "edition": "HR:hr", "query": "Hrvatska OR Zagreb"},
    "SI": {"name": "Slovenia", "locale": "sl", "edition": "SI:sl", "query": "Slovenija OR Ljubljana"},
    "TR": {"name": "Türkiye", "locale": "tr", "edition": "TR:tr", "query": "Türkiye OR Ankara OR İstanbul"},
    "MD": {"name": "Moldova", "locale": "ro", "edition": "MD:ro", "query": "Moldova OR Chișinău"},
}
